[
  {
    _id: "breakingcad6000",
    company_name: "Breaking Cad",
    company_staff: ["walterwa1", "jesspink2", "sgoodman3"],
    company_address: {
      address_line1: "3828 Piermont Drive",
      address_line2: "",
      address_city: "Alburquerque",
      address_region: "New Mexico",
      address_country: "USA",
      address_postcode: "91764",
    },
    company_phoneNumbers: [
      { key: "saul", value: "505503445" },
      { key: "pollos", value: "5051460195" },
    ],
    company_numberOfEmployees: 3,
    company_emails: "ch3nh2@breakingcad.com",
    company_createdOn: "2008-01-20T09:00:00.000Z",
    company_activeTickets: 0,
    company_activeBugs: 2,
    company_activeProjects: ["heisenberg1"],
    company_broadcastMessages: [],
    company_licenseType: "business",
    company_licenseExpiryDate: null,
    company_github: "",
    company_isDeleted: false,
  },
];
