[
  {
    _id: "walterwa1",
    user_firstName: "Walter",
    user_lastName: "White",
    user_userName: "Heisenberg",
    user_email: "heisenberg62@breakingcad.com",
    user_company: "breakingcad6000",
    user_createdOn: "2008-01-20T09:00:00.000Z",
    user_address: {
      address_line1: "3828 Piermont Drive",
      address_line2: "",
      address_city: "Alburquerque",
      address_region: "New Mexico",
      address_country: "USA",
      address_postcode: "91764",
    },
    user_phoneNumbers: {
      work: "18002255324",
    },
    user_role: "admin",
    user_teams: ["blue sky"],
    user_isDeleted: false,
    user_ticketsCreated: 0,
    user_bugsRaised: 0,
    user_ticketsCompleted: 0,
    user_bugsResolved: 0,
    user_lastActive: "2008-01-20T09:00:00.000Z",
    user_avatar:
      "https://upload.wikimedia.org/wikipedia/en/0/03/Walter_White_S5B.png",
    user_personalNotes: {
      title: "Possible source of Methylamine",
      content:
        "Jesse knows a warehouse that's lightly guarded, building 3 chemical storage is where it's at",
    },
    user_licenseType: "business",
    user_licenseExpiryDate: null,
  },
  {
    _id: "jesspink2",
    user_firstName: "Jesse",
    user_lastName: "Pinkman",
    user_userName: "capNcook",
    user_email: "capncook@breakingcad.com",
    user_company: "breakingcad6000",
    user_createdOn: "2008-01-20T09:00:00.000Z",
    user_address: {
      address_line1: "9809 Margo Street",
      address_line2: "",
      address_city: "Alburquerque",
      address_region: "New Mexico",
      address_country: "USA",
      address_postcode: "87106",
    },
    user_phoneNumbers: {
      home: "5051483369",
    },
    user_role: "developer",
    user_teams: ["blue sky"],
    user_isDeleted: false,
    user_ticketsCreated: 0,
    user_bugsRaised: 0,
    user_ticketsCompleted: 0,
    user_bugsResolved: 0,
    user_lastActive: "2008-01-20T09:00:00.000Z",
    user_avatar:
      "https://static.wikia.nocookie.net/breakingbad/images/a/a2/JesseS4Promo_Portr%C3%A4t.jpg/revision/latest/scale-to-width-down/350?cb=20110807151107&path-prefix=de",
    user_personalNotes: {
      title: "Biatch",
      content: "sup biatch?",
    },
    user_licenseType: "free",
    user_licenseExpiryDate: null,
  },
  {
    _id: "sgoodman3",
    user_firstName: "Saul",
    user_lastName: "Goodman",
    user_userName: "betterCallSaul",
    user_email: "bettercall@saul.com",
    user_company: "breakingcad6000",
    user_createdOn: "2008-01-20T09:00:00.000Z",
    user_address: {
      address_line1: "9800 Montgomery Blvd NE",
      address_line2: "",
      address_city: "Alburquerque",
      address_region: "New Mexico",
      address_country: "USA",
      address_postcode: "87106",
    },
    user_phoneNumbers: {
      home: "5055034455",
      work: "5058425662",
      mobile: "5052427700",
    },
    user_role: "tester",
    user_teams: ["lawyers"],
    user_isDeleted: false,
    user_ticketsCreated: 0,
    user_bugsRaised: 0,
    user_ticketsCompleted: 0,
    user_bugsResolved: 0,
    user_lastActive: "2008-01-20T09:00:00.000Z",
    user_avatar:
      "https://static.wikia.nocookie.net/breakingbad/images/7/78/BB_Saul_Goodman.jpg/revision/latest?cb=20150505181712",
    user_licenseType: "charity",
    user_licenseExpiryDate: null,
  },
];
